openapi: 3.1.0
info:
  title: Simple Flask API
  description: A simple Flask-based API with basic endpoints
  version: 1.0.0
servers:
  - url: https://api-daaf-gcloud.replit.app
    description: Development server

paths:
  /:
    get:
      summary: Redirect to API docs
      description: This endpoint redirects to the API documentation.
      operationId: redirectToDocs
      responses:
        '302':
          description: Redirect to /apidocs
  /status:
    get:
      summary: Get API status
      description: Returns a status message.
      operationId: getStatusMessage
      responses:
        '200':
          description: Returns a simple status message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "API is accessible"
